version: "3.9"
services:
  mediawiki:
    image: mediawiki:latest
    ports:
      - "8080:80"
    volumes:
      - /home/root/docker/mediawiki/images:/var/www/html/images
      - /home/root/docker/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki_rw
      - MYSQL_PASSWORD=rbEd7aYCPTet
      - MYSQL_ROOT_PASSWORD=nbj7m63ASb6X
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:latest
    volumes:
     - /home/root/docker/mariadb:/var/lib/mysql
     - /home/root/docker/db_backups/:/backup
    environment:
      - MYSQL_DATABASE=my_wiki
      - MYSQL_USER=mediawiki_rw
      - MYSQL_PASSWORD=rbEd7aYCPTet
      - MYSQL_ROOT_PASSWORD=nbj7m63ASb6X
    restart: always